# script parameters
model_id: "ytcheng/llama-3-8b-hf-sm-lora-merged" # Hugging Face model id
dataset: "ytcheng/sm_kf_chat_message"                      # path to dataset
max_seq_len:  3072 # 2048              # max sequence length for model and packing of the dataset
# training parameters
push_to_hub: true
hub_model_id: "ytcheng/llama-3-8b-hf-ft-chat-lora_1"
output_dir: "./llama-3-8b-hf-ft-chat-lora_1" # Temporary output directory for model checkpoints
report_to: "all"               # report metrics to tensorboard
learning_rate: 0.0001                  # learning rate 2e-4
lr_scheduler_type: "cosine"          # learning rate scheduler
num_train_epochs: 8                    # number of training epochs
per_device_train_batch_size: 32         # batch size per device during training
per_device_eval_batch_size: 32          # batch size for evaluation
gradient_accumulation_steps: 2         # number of steps before performing a backward/update pass
optim: adamw_torch                     # use torch adamw optimizer
logging_steps: 10                      # log every 10 steps
save_strategy: epoch                   # save checkpoint every epoch
evaluation_strategy: epoch             # evaluate every epoch
max_grad_norm: 0.3                     # max gradient norm
warmup_ratio: 0.3                     # warmup ratio
bf16: true                             # use bfloat16 precision
tf32: true                             # use tf32 precision
gradient_checkpointing: true           # use gradient checkpointing to save memory
# resume_from_checkpoint: "./llama-3-8b-hf-sm/checkpoint-264"
# FSDP parameters: https://huggingface.co/docs/transformers/main/en/fsdp
fsdp: "full_shard auto_wrap offload" # remove offload if enough GPU memory
fsdp_config:
  backward_prefetch: "backward_pre"
  forward_prefetch: "false"
  use_orig_params: "false"
